import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const iran = localFont({
  src: '../../asset/IRANSans-Edit.ttf', // مطمئن شو مسیر درسته
  variable: '--font-iran',
  display: 'swap',
});


export const metadata = {
  title: "crypto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${iran.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
